name: caav
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

flutter:
  plugin:
    implements: camera
    platforms:
      ios:
        pluginClass: CameraPlugin
        dartPluginClass: AVFoundationCamera

dependencies:
  camera_platform_interface: ^2.7.0
  flutter:
    sdk: flutter
  stream_transform: ^2.0.0

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter